    # Step 1: Download Docker Compose
    - name: Download Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    # Step 2: Copy Docker Compose Monitoring File
    - name: Copy Docker Compose file to target machine
      ansible.builtin.copy:
        src: ../source/application/docker-compose.monitoring.yaml
        dest: /home/ubuntu/docker-compose.monitoring.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    # Step 3: Copy Prometheus Configuration File
    - name: Copy prometheus.yaml to the target machine
      copy:
        src: ../source/application/prometheus.yaml  # Update with your local path
        dest: /home/ubuntu/prometheus.yaml

    # Step 4: Copy Grafana Configuration File
    - name: Copy grafana.yaml to the target machine
      copy:
        src: ../source/application/grafana.yaml  # Update with your local path
        dest: /home/ubuntu/grafana.yaml

    # Step 5: Copy Loki Configuration File
    - name: Copy loki-config.yml to the target machine
      copy:
        src: ../source/application/loki-config.yaml  # Update with your local path
        dest: /home/ubuntu/loki-config.yaml

    # Step 6: Copy Promtail Configuration File
    - name: Copy promtail-config.yaml to the target machine
      copy:
        src: ../source/application/promtail-config.yaml  # Update with your local path
        dest: /home/ubuntu/promtail-config.yaml

    # Step 7: Change Ownership of Copied Configuration Files
    - name: Change ownership of copied files
      file:
        path: "{{ item }}"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      loop:
        - /home/ubuntu/docker-compose.monitoring.yaml
        - /home/ubuntu/prometheus.yaml
        - /home/ubuntu/grafana.yaml
        - /home/ubuntu/loki-config.yaml
        - /home/ubuntu/promtail-config.yaml       

    # Step 8: Bring Monitoring Services Up By Running Docker Compose Up
    - name: Run docker-compose up
      shell: docker-compose -f /home/ubuntu/docker-compose.monitoring.yaml up -d
      become: yes
      register: docker_compose_output
      #ignore_errors: yes

    # Step 9: Debug docker-compose output 
    - name: Debug docker-compose output
      debug:
        var: docker_compose_output
