---
# Task to ensure the directory for Nginx configuration is created with correct permissions
- name: Ensure Nginx configuration directory does not exist if incorrect
  ansible.builtin.file:
    path: "/home/ubuntu/nginx"
    state: absent
  become: yes

- name: Create directory for Nginx configuration
  ansible.builtin.file:
    path: "/home/ubuntu/nginx"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

# Task to copy the Nginx configuration file to the target machine
- name: Copy Nginx configuration to target machine
  ansible.builtin.copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: "/home/ubuntu/nginx/nginx.conf"
    owner: root
    group: root
    mode: '0644'
  become: yes

# Task to deploy Nginx container with the mounted configuration file
- name: Start or Restart Nginx container
  ansible.builtin.docker_container:
    name: nginx
    image: nginx:latest
    state: started
    restart_policy: unless-stopped
    volumes:
      - "/home/ubuntu/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "8081:80"
  become: yes
