name: CI - Application

on:
  push:
    branches:
      - integration

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and Tag Docker Image for Backend
    - name: Build Backend Docker Image
      working-directory: ./source/backend
      run: |
        docker build -t kappu1512/backend:${{ github.sha }} .
        docker tag kappu1512/backend:${{ github.sha }} your-dockerhub-username/backend:latest

    # Step 4: Build and Tag Docker Image for Frontend
    - name: Build Frontend Docker Image
      working-directory: ./source/frontend
      run: |
        docker build -t your-dockerhub-username/frontend:${{ github.sha }} .
        docker tag your-dockerhub-username/frontend:${{ github.sha }} your-dockerhub-username/frontend:latest

    # Step 5: Push Backend and Frontend Docker Images
    - name: Push Backend Docker Image
      run: |
        docker push kappu1512/backend:${{ github.sha }}
        docker push kappu1512/backend:latest

    - name: Push Frontend Docker Image
      run: |
        docker push kappu1512/frontend:${{ github.sha }}
        docker push kappu1512/frontend:latest

    # Step 6: Update docker-compose.yml with New Image Tags
    - name: Update docker-compose.yml
      working-directory: ./source/application
      run: |
        sed -i 's|image: kappu1512/backend:.*|image: kappu1512/backend:${{ github.sha }}|' docker-compose.yml
        sed -i 's|image: kappu1512/frontend:.*|image: kappu1512/frontend:${{ github.sha }}|' docker-compose.yml

    # Step 7: Commit and Push Changes to Integration Branch
    - name: Commit and Push Changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add ./source/application/docker-compose.yml
        git commit -m "Update docker-compose.yml with new image tags"
        git push origin integration
